name: Comma master-ci puller
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    inputs:
        name:
          description: 'Person to greet'
          required: true
          default: 'Mona the Octocat'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master-ci             # set the branch to merge to
          fetch-depth: 0
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: commaai/openpilot      # set the upstream repo
          upstream-branch: master-ci   # set the upstream branch to merge from
          branch: master-ci          # set the branch to merge to

